basePath: /api/v1
definitions:
  foodshare.DonatableObjType:
    enum:
    - FoodStuff
    - Cloths
    - MedicalSupplies
    - SchoolSupplies
    - PersonalCareSupplies
    - BooksAndToys
    type: string
    x-enum-varnames:
    - FoodStuff
    - Cloths
    - MedicalSupplies
    - SchoolSupplies
    - PersonalCareSupplies
    - BooksAndToys
  foodshare.DonationSerializer:
    properties:
      donation_date:
        type: string
      donation_type:
        $ref: '#/definitions/foodshare.DonatableObjType'
      donor_id:
        type: integer
      item_description:
        type: string
      pickup_address:
        $ref: '#/definitions/foodshare.DonationStatusType'
      title:
        type: string
    required:
    - donation_date
    - donor_id
    - pickup_address
    - title
    type: object
  foodshare.DonationStatusType:
    enum:
    - Pending
    - PickedUp
    type: string
    x-enum-varnames:
    - Pending
    - PickedUp
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /donations:
    get:
      description: list donations
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/foodshare.DonationSerializer'
      summary: List donations
    post:
      consumes:
      - application/json
      description: create a donation
      parameters:
      - description: Donation
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/foodshare.DonationSerializer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/foodshare.DonationSerializer'
      summary: Create a donation
  /donations/{uid}:
    delete:
      description: delete a donation
      parameters:
      - description: Donation UID
        in: path
        name: uid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete a donation
    get:
      description: get a donation
      parameters:
      - description: Donation UID
        in: path
        name: uid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/foodshare.DonationSerializer'
      summary: Get a donation
    patch:
      consumes:
      - application/json
      description: update a donation
      parameters:
      - description: Donation UID
        in: path
        name: uid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Update a donation
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
